import sys

from syscall_parser import (
    VALID_SYSCALL_VALUE_TYPES,
    Constant,
    SyscallDefinition,
    SyscallError,
    SyscallParser,
    Type,
)


def main():
    # Retrieve the toml path from the argv
    if len(sys.argv) != 3:
        print(
            "Usage: python syscall_aether_sys_gen.py <path_to_syscalls.toml> <path_to_errors.toml>",
            file=sys.stderr,
        )
        sys.exit(1)
        pass
    toml_path = sys.argv[1]
    errors_path = sys.argv[2]
    parser = SyscallParser([toml_path, errors_path])
    generated_output = parser.generate(adapter=SyscallAetherSysAdapter())

    print("""
// This file is automatically generated by syscall_aether_sys_gen.py. Do not edit manually.
#![no_std]
#![allow(dead_code)]\n
    """)
    print("""
#[inline(always)]
unsafe fn do_syscall(syscall_number: u64, arg0: u64, arg1: u64, arg2: u64, arg3: u64, arg4: u64) -> Result<u64, SyscallError> {
    let mut ret: u64 = 0;
    let mut err_code: u64 = 0;
    unsafe {
        #[cfg(target_arch = "x86_64")]
        core::arch::asm!(
            "syscall",
            inout("rax") syscall_number => ret,
            inout("rdi") arg0 => _,
            inout("rsi") arg1 => _,
            inout("rdx") arg2 => err_code,
            inout("r10") arg3 => _,
            inout("r8") arg4 => _,
            // clobbers
            out("rcx") _,
            out("r9") _,
            out("r11") _,
        );
        #[cfg(target_arch = "aarch64")]
        core::arch::asm!(
            "svc #0",
            in("x8") syscall_number,
            inout("x0") arg0 => ret,
            inout("x1") arg1 => err_code,
            in("x2") arg2,
            in("x3") arg3,
            in("x4") arg4,
        );
    }
    if err_code != 0 {
        Err(SyscallError::from_code(err_code))
    } else {
        Ok(ret)
    }
}\n
    """)

    for syscall in generated_output.syscalls:
        print(syscall)
        print()
        pass

    print("\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    print("#[repr(u64)]")
    print("pub enum SyscallError {")
    for error in generated_output.errors:
        print(error[0])
        pass
    print("}\n")
    print("""
impl SyscallError {
    pub fn from_code(code: u64) -> Self {
        match code {
    """)
    for error in generated_output.errors:
        print(error[1])
        pass
    print("""
            _ => panic!("Unknown syscall error code: {}", code),
        }
    }
}
    """)

    for constant in generated_output.constants:
        print(constant)
        pass

    print("Generated syscall definitions successfully!", file=sys.stderr)
    pass


def snake_case_to_upper_camel_case(snake_str: str) -> str:
    components = snake_str.split("_")
    return "".join(x.title() for x in components)


class SyscallAetherSysAdapter:
    def translate_type(self, type_obj: Type) -> str:
        # We handle return types slightly differently to match legacy uintptr_t/void
        TYPE_TRANSLATION = {
            "unit": "()",
            "uint8": "u8",
            "uint32": "u32",
            "uint64": "u64",
            "int32": "i32",
            "uptr": "*mut u8",
            "usize": "usize",
            "const uint8*": "*const u8",
        }

        for valid_type in VALID_SYSCALL_VALUE_TYPES:
            assert valid_type in TYPE_TRANSLATION, (
                f"Missing translation for type: {valid_type}"
            )
            pass

        return TYPE_TRANSLATION[type_obj.name]

    def render_syscall(self, syscall: SyscallDefinition) -> str:
        return_type = self.translate_type(syscall.return_type)
        name = syscall.name.lower()

        fn_args = ", ".join(
            [f"{arg.name}: {self.translate_type(arg.type)}" for arg in syscall.args]
        )

        body_args = ", ".join([f"({arg.name} as u64)" for arg in syscall.args])
        if len(syscall.args) == 0:
            body_args = "0, 0, 0, 0, 0"
            pass
        else:
            for _ in range(5 - len(syscall.args)):
                body_args += ", 0"
                pass
            pass

        if syscall.return_type.name != "unit":
            return_expr = f"Ok(ret as {return_type})"
            pass
        else:
            return_expr = "Ok(())"
            pass

        return f"""
pub unsafe fn sys_{name}({fn_args}) -> Result<{return_type}, SyscallError> {{
    #[allow(unused_variables)]
    #[allow(unused_parens)]
    unsafe {{
        let ret: u64 = do_syscall({hex(syscall.number)}, {body_args})?;
        {return_expr}
    }}
}}
"""

    def render_constant(self, constant: Constant) -> str:
        name = f"SYS_{constant.name.upper()}"
        value = hex(constant.value)
        type = self.translate_type(constant.type)
        return f"pub const {name}: {type} = {value};"

    def render_error(self, error: SyscallError) -> list[str]:
        name = snake_case_to_upper_camel_case(error.name)
        code = hex(error.code)
        message = error.message
        return [
            f"    {name} = {code}, // {message}",
            f"{code} => SyscallError::{name},",
        ]


if __name__ == "__main__":
    main()
    sys.exit(0)
