from syscall_parser import VALID_SYSCALL_VALUE_TYPES, Constant, SyscallDefinition, SyscallError, SyscallParser, Type
import sys

def main():
    # Retrieve the toml path from the argv
    if len(sys.argv) != 3:
        print("Usage: python compat_generator.py <path_to_syscalls.toml> <path_to_errors.toml>", file=sys.stderr)
        sys.exit(1)
        pass
    toml_path = sys.argv[1]
    errors_path = sys.argv[2]
    parser = SyscallParser([toml_path, errors_path])
    generated_output = parser.generate(adapter=SyscallKernelAdapter())

    print("""
// This file is automatically generated by syscall_kernel_gen.py. Do not edit manually.
#![no_std]
#![allow(dead_code)]
    """)

    print("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    print("#[repr(u64)]")
    print("pub enum SyscallNumber {")
    for syscall in generated_output.syscalls:
        print(syscall)
        pass
    print("}\n\n// Constants")

    for constant in generated_output.constants:
        print(constant)
        pass

    print("\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    print("#[repr(u64)]")
    print("pub enum SyscallError {")
    for error in generated_output.errors:
        print(error)
        pass
    print("}")

    print("Generated syscall kernel definitions successfully!", file=sys.stderr)
    pass

def snake_case_to_upper_camel_case(snake_str: str) -> str:
    components = snake_str.split('_')
    return ''.join(x.title() for x in components)

class SyscallKernelAdapter:
    def translate_type(self, type_obj: Type) -> str:
        # We handle return types slightly differently to match legacy uintptr_t/void
        TYPE_TRANSLATION = {
            "unit": "()",
            "uint8": "u8",
            "uint32": "u32",
            "uint64": "u64",
            "int32": "i32",
            "uptr": "*mut ::core::ffi::c_void",
            "usize": "usize",
            "const uint8*": "*const u8",
        }

        for valid_type in VALID_SYSCALL_VALUE_TYPES:
            assert valid_type in TYPE_TRANSLATION, f"Missing translation for type: {valid_type}"
            pass

        return TYPE_TRANSLATION[type_obj.name]

    def render_syscall(self, syscall: SyscallDefinition) -> str:
        return_type = self.translate_type(syscall.return_type)
        name = snake_case_to_upper_camel_case(syscall.name)

        return f"    {name} = {syscall.number},"

    def render_constant(self, constant: Constant) -> str:
        name = f"SYS_{constant.name.upper()}"
        value = hex(constant.value)
        type = self.translate_type(constant.type)
        return f"pub const {name}: {type} = {value};"

    def render_error(self, error: SyscallError) -> str:
        name = snake_case_to_upper_camel_case(error.name)
        code = hex(error.code)
        message = error.message
        return f"    {name} = {code}, // {message}"

if __name__ == "__main__":
    main()
    sys.exit(0)
