[book]
title = "Aether documentation"
authors = [
    "Richard Tichý",
]
language = "en"

[output.html]
site-url = "/aether/"
git-repository-url = "https://github.com/ArtifyCZ/aether"
git-repository-icon = "fab-github"
